services:
  couchdb:
    image: couchdb:3
    container_name: obsidian_sync
    env_file: .env
    volumes:
      - /opt/obsidianRemote/couchdb/data:/opt/couchdb/data
      - /opt/obsidianRemote/couchdb/config:/opt/couchdb/etc/local.d
    restart: unless-stopped
    networks:
      - npm_default

networks:
  npm_default:
    external: true
