[httpd]
enable_cors = true

[cors]
; Obsidian desktop uses app://obsidian.md, mobile uses capacitor://localhost
origins = app://obsidian.md,capacitor://localhost,http://localhost
credentials = true
methods = GET, PUT, POST, HEAD, DELETE
headers = accept, authorization, content-type, origin, referer
